name: Test Runner

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Debug user
        shell: powershell
        run: |
          whoami
          echo $env:USERPROFILE

      - name: Create file on Desktop
        shell: powershell
        run: |
          $desktop = "C:\Users\Administrator\Desktop"
          $file = Join-Path $desktop "durgesh.txt"
          "Durgesh test runner" | Out-File -FilePath $file -Encoding utf8

      - name: Confirm file created
        shell: powershell
        run: |
          Get-ChildItem "C:\Users\Administrator\Desktop"
