name: Test Runner 1

on: [push]

jobs:
  build:
    name: Test on Runner 1
    runs-on: [self-hosted, windows, server-2019, runner-1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create file on Desktop with text
        shell: powershell
        run: |
          $desktop = "$env:USERPROFILE\Desktop"
          $file = Join-Path $desktop "test1.txt"
          "test" | Out-File -FilePath $file -Encoding utf8
      - name: Confirm file created
        shell: powershell
        run: |
          $desktop = "$env:USERPROFILE\Desktop"
          Get-ChildItem $desktop
